### PR TITLE
Ignore tokens that belong to array element declaration

### LINKED ISSUE #3059: Squiz.Arrays.ArrayDeclaration false positive when using type casting
**Describe the bug**
A false-positive rule violation is detected that conflicts with another rule and prevents auto-fixing.

**Code sample**
```php
<?php

function test()
{
    return [
        (object) [
            'a' => 'foo',
            'b' => 1,
        ],
    ];
}
```

**Custom ruleset**
None.

**To reproduce**
1. Run `phpcs -s --standard=Squiz --sniffs=Squiz.Arrays.ArrayDeclaration,Generic.Formatting.SpaceAfterCast fail.php`
```
FILE: /home/morozov/Projects/phpcs-playground/fail.php
------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------
 6 | ERROR | [x] The first value in a multi-value array must be on a new line
   |       |     (Squiz.Arrays.ArrayDeclaration.ValueNoNewline)
------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------

Time: 47ms; Memory: 8MB
```
2. Run `phpcbf --standard=Squiz --sniffs=Squiz.Arrays.ArrayDeclaration,Generic.Formatting.SpaceAfterCast fail.php`
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
/home/morozov/Projects/phpcs-playground/fail.php     FAILED TO FIX
----------------------------------------------------------------------
A TOTAL OF 0 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------
PHPCBF FAILED TO FIX 1 FILE
----------------------------------------------------------------------

Time: 124ms; Memory: 8MB
```

**Expected behavior**
No error is reported.

**Versions (please complete the following information):**
 - OS: Linux
 - PHP: 7.4.9
 - PHPCS: 3.5.6
 - Standard: Squiz

### LINKED ISSUE #3060: Squiz.Arrays.ArrayDeclaration false positive for static functions
**Describe the bug**
A false-positive rule violation is detected that prevents auto-fixing.

**Code sample**
```php
<?php

function test()
{
    yield [
        static function (): void {
        },
    ];
}
```

**Custom ruleset**
None.

**To reproduce**
1. Run `phpcs -s --standard=Squiz --sniffs=Squiz.Arrays.ArrayDeclaration,Squiz.WhiteSpace.ScopeKeywordSpacing test.php`
```
FILE: /home/morozov/Projects/phpcs-playground/test.php
------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------
 6 | ERROR | [x] The first value in a multi-value array must be on a new line
   |       |     (Squiz.Arrays.ArrayDeclaration.ValueNoNewline)
------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------

Time: 44ms; Memory: 8MB
```
2. Run `phpcbf --standard=Squiz --sniffs=Squiz.Arrays.ArrayDeclaration,Squiz.WhiteSpace.ScopeKeywordSpacing test.php`
```
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
/home/morozov/Projects/phpcs-playground/test.php      FAILED TO FIX
----------------------------------------------------------------------
A TOTAL OF 0 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------
PHPCBF FAILED TO FIX 1 FILE
----------------------------------------------------------------------

Time: 95ms; Memory: 8MB
```

**Expected behavior**
No error is reported.

**Versions (please complete the following information):**
 - OS: Linux
 - PHP: 7.4.9
 - PHPCS: 3.5.6
 - Standard: Squiz

### PR DESCRIPTION
**Pull request by morozov**
- [x] Ignore `T_*_CAST` to allow `(cast) ...` array elements. Fixes #3059.
- [x] Ignore `T_STATIC` before `T_CLOSURE` to allow `static function` array elements. Fixes #3060.

### CODE REVIEW

File: src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php [hunk 1]
```diff
@@ -620,7 +620,23 @@ public function processMultiLineArray($phpcsFile, $stackPtr, $arrayStart, $array
...
+                    T_WHITESPACE,
+                    T_COMMA,
+                    T_ARRAY_CAST,
+                    T_BOOL_CAST,
+                    T_DOUBLE_CAST,
+                    T_INT_CAST,
+                    T_OBJECT_CAST,
+                    T_STRING_CAST,
+                    T_UNSET_CAST,
+                ];
```
Comment (jrfnl) [inline src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php:633]: You may want to use the preset `Tokens::`$castTokens` array here.

**Comment by morozov** [comment]
@gsherwood what's your plan on reviewing this and other PRs?

**Comment by gsherwood** [comment]
> @gsherwood what's your plan on reviewing this and other PRs?

Just needed time mate.

Thanks a lot for these fixes, and the detailed bug reports.
