### PR TITLE
Specified array and callback docblock types

### LINKED ISSUE #601: Expected type hint int[]; found array in Squiz FunctionCommentSniff
**Example code:**

```php
	/**
	 * Does foo with IDs.
	 *
	 * @param int[] $ids List of IDs.
	 */
	function foo( array $ids ) {}
```

**Expected result:**
This should be OK.

**Actual result:**

```
 4   | ERROR | Expected type hint "int[]"; found "array" for $ids
     |       | (Squiz.Commenting.FunctionComment.IncorrectTypeHint)
 ```

---

The error comes from https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php#L386.

### PR DESCRIPTION
**Pull request by scato**
In reaction to #685, I've looked around the code base, but I haven't found any other sniffs that relate to array type hints.

I have found another inconsistency in callable/callback. I've asked the phpDocumenter team for clarification: https://github.com/phpDocumentor/phpDocumentor2/issues/1645

On top of that, I've added tests.

(This PR would also fix #601 and #642.)

### CODE REVIEW

File: CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php [hunk 1]
```diff
@@ -650,10 +650,12 @@ protected function processParams($commentStart, $commentEnd)
                     } else if (count($typeNames) === 1) {
                         // Check type hint for array and custom type.
                         $suggestedTypeHint = '';
-                        if (strpos($suggestedName, 'array') !== false) {
+                        if (strpos($suggestedName, 'array') !== false || substr($suggestedName, -2) === '[]') {
```
Comment (aik099) [inline CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php]: This does cover basic `ClassName[]` format, but doesn't cover more complex ones, like `integer[]|string` or `(classA|classB)|(classC[])`. I personally don't use such complex types in DocBlocks, but PhpDoc supports them.

Supporting them might be bad for performance reasons (because you need to parse whole type string).

File: CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php [hunk 2]
```diff
@@ -650,10 +650,12 @@ protected function processParams($commentStart, $commentEnd)
...
                             $suggestedTypeHint = 'array';
                         } else if (strpos($suggestedName, 'callable') !== false) {
                             $suggestedTypeHint = 'callable';
+                        } else if (strpos($suggestedName, 'callback') !== false) {
```
Comment (aik099) [inline CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php]: Is `callback` some new type? I've never seen PHP type hint as `callback`.

File: CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php (hunk 1 above)
Comment (scato) [inline CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php]: If there is a | in the type, count($typeNames) will be greater than 1, and no type hint will be suggested. In other words: this piece of code doesn't have to cover composite types.

Comment (aik099) [inline CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php]: Good.

File: CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php (hunk 2 above)
Comment (scato) [inline CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php]: It has never been a type, but has been allowed in @param tags. $suggestedName matches the type in the @param tag, $suggestedTypeHint matches the @param tag.

**Comment by gsherwood** [comment]
I can't merge this in because you've made a PR from the old unsupported 1.x version. As the changes are so small, I can apply them manually, but I thought I'd let you know in case you want to create a new PR based on the current supported code.

Let me know if you'd prefer me to manually apply the changes.

**Comment by scato** [comment]
Thanks!

I had already started on a rebase, so I'd thought I just finish it real quick. So here it is. :)

**Comment by scato** [comment]
I see I have a merge commit, do you want me to fix that?

**Comment by scato** [comment]
never mind :)

**Comment by gsherwood** [comment]
Thanks a lot for doing that, and for the PR, and for the tests!

**Comment by scato** [comment]
No problem!
